# Generated by Django 5.2.11 on 2026-03-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "account_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=50
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=3
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
                ("is_include_in_total", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Budgets",
            fields=[
                (
                    "budget_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "budget_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=100
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "period",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=20
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("alert_threshold", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "budgets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "category_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=100
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=20
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("is_default", models.BooleanField()),
                ("is_deleted", models.BooleanField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DebtPayment",
            fields=[
                (
                    "payment_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "debt_payment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Debts",
            fields=[
                (
                    "debt_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "debt_type",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "person_name",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "debts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=50
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField()),
                (
                    "related_id",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notification",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "permission_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RecurringTransactions",
            fields=[
                (
                    "recurring_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=50
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("next_occurrence_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "recurring_transactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RolePermissions",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "role_id",
                        "permission_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "role_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "role_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SavingsGoals",
            fields=[
                (
                    "goal_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "goal_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=200
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "current_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("target_date", models.DateField()),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "savings_goals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SharedAccess",
            fields=[
                (
                    "share_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shared_access",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "transaction_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "transaction_type",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=20
                    ),
                ),
                ("transaction_date", models.DateTimeField()),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "receipt_image_url",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_recurring", models.BooleanField()),
                (
                    "recurring_id",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "transactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transfers",
            fields=[
                (
                    "transfer_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("transfer_date", models.DateField()),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "transfers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=100
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=100
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=100
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=30
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=3,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "setting_id",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("enable_notification", models.BooleanField(blank=True, null=True)),
                ("budget_alert_enabled", models.BooleanField(blank=True, null=True)),
                ("weekly_report_enabled", models.BooleanField(blank=True, null=True)),
                ("monthly_report_enabled", models.BooleanField(blank=True, null=True)),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_setting",
                "managed": False,
            },
        ),
    ]
