from django.db import transaction as db_transaction
from django.utils import timezone
from datetime import datetime
from uuid import uuid4
from api.models import RecurringTransactions, Accounts, Categories
from api.services.transaction_service import TransactionService
import logging

logger = logging.getLogger(__name__)

class RecurringService:
    @staticmethod
    def get_active_recurrings(user):
        return RecurringTransactions.objects.filter(user=user, is_active=True).order_by('-created_at')

    @staticmethod
    def create_recurring(validated_data, user):
        with db_transaction.atomic():
            recurring_id = f'REC-{str(uuid4())[:15]}'
            now = timezone.now()

            record = RecurringTransactions.objects.create(
                recurring_id=recurring_id,
                user=user,
                account=validated_data['account'],
                category=validated_data['category'],
                amount=validated_data['amount'],
                transaction_type=validated_data['transaction_type'],
                description=validated_data.get('description', ''),
                frequency=validated_data['frequency'],
                start_date=validated_data['start_date'],
                end_date=validated_data['end_date'],
                next_occurrence_date=validated_data['start_date'], # khởi tạo lần đàu tiên là start date
                is_active=True,
                created_at=now
            )
        return record

    @staticmethod
    def update_recurring(recurring_obj, validated_data, user):
        with db_transaction.atomic():
            if 'account_id' in validated_data:
                recurring_obj.account = Accounts.objects.get(account_id=validated_data.pop('account_id'), user=user)
            if 'category_id' in validated_data:
                recurring_obj.category = Categories.objects.get(category_id=validated_data.pop('category_id'), user=user)
            
            for key, value in validated_data.items():
                setattr(recurring_obj, key, value)
            
            # Nếu user đổi start_date, reset lại kỳ lặp
            if 'start_date' in validated_data:
                recurring_obj.next_occurrence_date = validated_data['start_date']

            recurring_obj.save()
        return recurring_obj

    @staticmethod
    def delete_recurring(recurring_id, user):
        with db_transaction.atomic():
            record = RecurringTransactions.objects.get(recurring_id=recurring_id, user=user, is_active=True)
            record.is_active = False 
            record.save()
            return True

    @staticmethod
    def process_daily_recurring():
        """Được gọi bởi Cronjob tự động hàng ngày lúc 00:00"""
        today = timezone.now().date()
        active_recurrings = RecurringTransactions.objects.filter(is_active=True, next_occurrence_date__lte=today)
        
        count = 0
        for recurring in active_recurrings:
            try:
                due_date = recurring.next_occurrence_date
                trans_datetime = timezone.make_aware(datetime.combine(due_date, datetime.min.time()))
                
                trans_data = {
                    'account': recurring.account, 'category': recurring.category, 'amount': recurring.amount,
                    'transaction_type': recurring.transaction_type, 'transaction_date': trans_datetime,
                    'description': recurring.description or f'Giao dịch tự động ({recurring.frequency})',
                    'note': 'Generated by System Cronjob', 'location': '', 'receipt_image_url': '',
                    'is_recurring': True, 'recurring_id': recurring.recurring_id
                }
                
                TransactionService.create_transaction(trans_data, recurring.user)
                count += 1
            except Exception as e:
                logger.error(f"Error processing recurring {recurring.recurring_id}: {str(e)}", exc_info=True)
        return count
